config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'posts#index'
  resources :posts do
    resources :comments
  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments
  validates :name, presence: true,
            length: { minimum: 5 }
  mount_uploader :image, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params)
    redirect_to post_path(@post)
  end

  private
    def comment_params
      params.require(:comment).permit(:commenter, :body)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @posts = Post.all
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])

    if @post.update(post_params)
      redirect_to root_path
    else
      render 'edit'
    end
  end

  def new
    @post = Post.new
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    redirect_to root_path
  end

  def show
    @post = Post.find(params[:id])
  end

  def create
    @post = Post.new(post_params)

    # respond_to do |format|
    #   if @post.save
    #     format.html { redirect_to @post, notice: 'Post successfully created'}
    #   else
    #     format.html { render :new}
    #     format.json { render json: @post.errors, status: :unprocessable_entity}
    #   end
    # end
    @post.save
    redirect_to @post
  end



  private
  def post_params
    params.require(:post).permit(:name, :content, :image, :commenter, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/edit.html.erb
<%= form_for :post, url: post_path(@post), method: :patch do |f| %>
    Name: <%= f.text_field :name %> <br>
    Content: <%= f.text_area :content %> <br>
    <%= f.submit %>
<% end %>

<% link_to 'Назад', posts_path %>

app/views/posts/index.html.erb
<div class="header">
  <p>I <span>write</span> here</p>
</div>

<div class="main">
  <div class="container">
    <% @posts.each do |post| %>

      <div class="post">
        <h1><%= post.name %></h1>
        <p class="time"><%= post.created_at %></p>
        <div class="image">
          <%= image_tag(post.image.url, alt: 'Image', width: 320) if post.image? %>
        </div>
        <p class="content"><%= post.content %></p>
        <div class="footer">
          <a class="comments" href="#">43 комментария</a>
          <%=link_to 'Перейти', (post)%>
        </div>
      </div>

    <% end %>
  </div>
</div>

app/views/posts/new.html.erb
<%= form_for @post do |f| %>
  Name: <%= f.text_field :name %> <br>
  Content: <%= f.text_area :content %> <br>
    <%= f.file_field :image %>
  <%= f.submit %>
<% end %>

app/views/posts/show.html.erb
  <%= link_to 'Назад', posts_path, class: "show_link" %> 
  <div class="container">
    <div class="post">
      <h1> <%= @post.name %></h1>
      <p class="time">21:28</p>
      <div class="image">
        <%= image_tag(@post.image_url, width: 320) if @post.image? %>
      </div>
      <p class="content"> <%= @post.content %></p>
      <div class="comments_block">
        <h1 class="comment_title">Комментарии:</h1>

        <ul class="comments_list">
        <% @post.comments.each do |comment| %>
          <li>
            <h1><%= comment.commenter %></h1>
            <p> <%= comment.body %> </p>
          </li>
          <% end %>
        </ul>
        <div class="comment_input">
          <h3>Оставить комментарии</h1>
          <%= form_with(model: [ @post, @post.comments.build ], local: true) do |form| %>
           <label>Имя:</label>
          <%= form.text_field :commenter, class: "name" %>
           <%= form.text_area :body, class: "content" %>
           <%= form.submit %>
          <% end %>
      </div>
      </div>
    </div>
  </div>